.PHONY: all clean disk

all:
	$(MAKE) -C .. -f makefiles/build.mk TARGET=msdos

disk:
	$(MAKE) -C .. -f makefiles/build.mk TARGET=msdos disk

clean:
	$(MAKE) -C .. -f makefiles/build.mk TARGET=msdos clean
