        .globl  _fn_calc_checksum_asm
        .globl  _fn_calc_checksum_asm_branch

;# uint8_t fn_calc_checksum_asm(const uint8_t *data, uint16_t len)
;#
;# Arguments, Amiga m68k ABI:
;#
;#   4(sp)   = data pointer
;#   8(sp)   = 4-byte stack slot for len
;#   10(sp)  = low word of that slot, i.e. uint16_t len
;#
;# Return:
;#
;#   D0.b = checksum
;#
;# Algorithm:
;#
;#   chk = 0;
;#   for each byte:
;#       sum = chk + byte;
;#       chk = (sum & 0xff) + (sum >> 8);
;#
;# Since chk and byte are each 0..255:
;#
;#   sum <= 0xff + 0xff = 0x1fe
;#
;# therefore the high byte can only ever be 0 or 1.
;#
;# So this can be implemented as:
;#
;#   chk = chk + byte + carry
;#
;# using ADD.B followed by ADDX.B.
;#
;# This version differs from the earlier one in one important way:
;#
;#   OLD:
;#       DBRA D1,.loop
;#
;#   NEW:
;#       compare current pointer against an end pointer
;#
;# This mirrors the loop structure generated by GCC:
;#
;#       end = data + len;
;#       while (data != end) ...
;#
;# The idea is to see whether this translates better under PiStorm/Emu68
;# than the very 68k-specific DBRA instruction.
;# It does, the PiStorm is quicker this way, but this is just for illustration.

_fn_calc_checksum_asm:

        ;# Load data pointer.
        move.l  4(%sp),%a0

        ;# Load uint16_t length.
        move.w  10(%sp),%d1


        ;# We use D2 as a scratch register / permanent zero for ADDX.
        ;#
        ;# D2 is callee-saved, so preserve the caller's value.
        move.l  %d2,-(%sp)


        ;# D0 holds the checksum and eventual return value.
        moveq   #0,%d0


        ;# len == 0?
        ;#
        ;# If so, checksum is already zero and we can return immediately.
        tst.w   %d1
        beq.s   .done


        ;# Build an end pointer:
        ;#
        ;#   A1 = A0 + len
        ;#
        ;# We cannot directly use D1.l here without first zero-extending it.
        ;#
        ;# MOVE.W only replaces the low 16 bits of a data register; the upper
        ;# 16 bits may contain garbage. So first clear D2 completely, then
        ;# copy the 16-bit length into its low word.
        moveq   #0,%d2
        move.w  %d1,%d2

        ;# A1 now points one byte past the final input byte.
        ;#
        ;# Example:
        ;#
        ;#   A0  = 0x1000
        ;#   len = 4
        ;#
        ;# gives:
        ;#
        ;#   A1  = 0x1004
        ;#
        ;# The loop processes bytes at:
        ;#
        ;#   0x1000
        ;#   0x1001
        ;#   0x1002
        ;#   0x1003
        ;#
        ;# and stops when A0 reaches 0x1004.
        lea     (%a0,%d2.l),%a1


        ;# D2 is no longer needed for the length.
        ;#
        ;# Clear it again so ADDX.B can use it as a permanent zero:
        ;#
        ;#   D0.b = D0.b + 0 + X
        ;#
        moveq   #0,%d2


.loop:

        ;# Add next byte into the low byte of the checksum.
        ;#
        ;# (%a0)+ means:
        ;#
        ;#   read from [A0]
        ;#   then increment A0
        ;#
        ;# Since the operand size is .B, A0 advances by 1.
        ;#
        ;# Example:
        ;#
        ;#   D0.b = 0xf0
        ;#   byte = 0x30
        ;#
        ;# 0xf0 + 0x30 = 0x120
        ;#
        ;# ADD.B stores:
        ;#
        ;#   D0.b = 0x20
        ;#
        ;# and sets X=1 because there was a carry out of bit 7.
        add.b   (%a0)+,%d0


        ;# Fold the carry back into the low byte.
        ;#
        ;# ADDX means "add with extend":
        ;#
        ;#   destination = destination + source + X
        ;#
        ;# D2 is zero, so:
        ;#
        ;#   D0.b = D0.b + X
        ;#
        ;# Continuing the example:
        ;#
        ;#   D0.b = 0x20
        ;#   X    = 1
        ;#
        ;# becomes:
        ;#
        ;#   D0.b = 0x21
        ;#
        ;# which is exactly:
        ;#
        ;#   (0x120 & 0xff) + (0x120 >> 8)
        ;#
        addx.b  %d2,%d0


        ;# Have we reached the end pointer?
        ;#
        ;# CMP is effectively:
        ;#
        ;#   A0 - A1
        ;#
        ;# but throws away the result and only updates the condition codes.
        ;#
        ;# BNE loops while A0 != A1.
        ;#
        ;# This is a very regular branch:
        ;#
        ;#   taken
        ;#   taken
        ;#   taken
        ;#   ...
        ;#   not taken
        ;#
        ;# which may be friendlier to PiStorm/Emu68 than DBRA.
        cmp.l   %a1,%a0
        bne.s   .loop


.done:

        ;# Restore caller's D2.
        move.l  (%sp)+,%d2

        ;# D0 already contains the uint8_t checksum.
        rts

;# uint8_t fn_calc_checksum_asm_branch(const uint8_t *data, uint16_t len)
;#
;# Same checksum as:
;#
;#   chk = 0;
;#   for (i = 0; i < len; i++) {
;#       sum = chk + data[i];
;#       chk = (sum & 0xff) + (sum >> 8);
;#   }
;#
;# Since chk and data[i] are both 0..255, sum is at most 0x1fe.
;# Therefore the high byte is only ever 0 or 1.
;#
;# This version handles that carry explicitly with BCC/ADDQ rather than ADDX.
;#
;# Inner loop:
;#
;#       add.b   (%a0)+,%d0
;#       bcc.s   .no_carry
;#       addq.b  #1,%d0
;#   .no_carry:
;#       dbra    %d1,.loop
;#
;# Unlike the ADDX version, this needs no zero scratch register, so D2 is not
;# touched and there is nothing to save/restore.
;# Although this benchmarks better on AmiBerry than both the C and above ASM
;# for smaller sizes, it is terrible on PiStorm/Emu68, due tothe branch prediction
;# failure in the Arm processor.

_fn_calc_checksum_asm_branch:

        ;# Fetch arguments.
        ;#
        ;# 4(sp)  = data pointer
        ;# 10(sp) = low word of uint16_t len's four-byte stack slot
        move.l  4(%sp),%a0
        move.w  10(%sp),%d1

        ;# D0 is the checksum/result.
        moveq   #0,%d0

        ;# A zero-length input returns checksum 0 immediately.
        tst.w   %d1
        beq.s   .done_b

        ;# DBRA performs N iterations when initialized to N-1.
        subq.w  #1,%d1

.loop_b:
        ;# Add the next byte into the low byte of D0.
        ;#
        ;# (%a0)+ means:
        ;#
        ;#   read from address A0
        ;#   then advance A0 by the operand size
        ;#
        ;# Since this is ADD.B, A0 advances by one byte.
        ;#
        ;# If the byte addition exceeds 0xff, the carry flag C is set.
        ;#
        ;# Example:
        ;#
        ;#   D0.b = 0xf0
        ;#   byte = 0x30
        ;#
        ;#   0xf0 + 0x30 = 0x120
        ;#
        ;# After ADD.B:
        ;#
        ;#   D0.b = 0x20
        ;#   C     = 1
        add.b   (%a0)+,%d0

        ;# BCC = Branch if Carry Clear.
        ;#
        ;# If there was no carry out of the byte addition, the checksum is
        ;# already correct and we can skip the carry fold.
        ;# TERRIBLE ON PiStorm/Emu68
        bcc.s   .no_carry

        ;# There was a carry, so fold it back into the low byte.
        ;#
        ;# Continuing the example:
        ;#
        ;#   D0.b = 0x20
        ;#
        ;# becomes:
        ;#
        ;#   D0.b = 0x21
        ;#
        ;# which is exactly:
        ;#
        ;#   (0x120 & 0xff) + (0x120 >> 8)
        ;#
        ;#   0x20 + 1
        addq.b  #1,%d0

.no_carry:
        ;# Decrement the low word of D1 and branch until it becomes 0xffff.
        dbra    %d1,.loop_b

.done_b:
        ;# D0 already contains the uint8_t result.
        rts